import "./globals.css";

export const metadata = {
  title: "Syncthon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="bg-white h-screen w-screen">{children}</div>
      </body>
    </html>
  );
}
