import { Control } from "./Control";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by YoonHeeHan",
};

export default async function RootLayout({ children }) {
  const topics = await fetch(process.env.NEXT_PUBLIC_API_URL + "topics", {
    cache: "no-store",
  }).then((resp) => resp.json());
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li>
                <Link key={topic.id} href={`/read/${topic.id}`}>
                  {topic.title}
                </Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
